version: '2'

services:
    srpago-oxxo:
        container_name: netcore2
        restart: always
        image: danteay/ubuntu-netcore:latest
        working_dir: /app
        command: dotnet run
        environment:
          APP_NAME: ""
          API_KEY: "asdasdasdasdasd"
          PORT: 5001
        ports:
            - 5001:5001
        volumes:
            - .:/app
